# @package _group_

common:
  fp16: false
  log_interval: 2
  wandb_project: SL_TD

task:
  _name: SL_topic_detection
  feats_type: ???
  body_parts: upperbody,lefthand,righthand
  feat_dims: "0,1,2"
  modeling_task: classification
  num_labels: 10
  data: ???
  dict_path: ???
  normalize: true
  min_source_positions: 150
  max_source_positions: 5500
  max_target_positions: 1

dataset:
  num_workers: 0
  max_tokens: 20000  # batch_size is inferred from max_tokens as the max num of sequences that can be fit in max_tokens
  skip_invalid_size_inputs_valid_test: true
  train_subset: train
  valid_subset: val
  validate_interval_updates: 600

criterion:
  _name: label_smoothed_cross_entropy

optimization:
  max_update: 4500
  lr: [1e-4]
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: [0.9, 0.998]
  weight_decay: 1e-3

lr_scheduler:
  _name: reduce_lr_on_plateau
  lr_shrink: 0.5
  lr_patience: 8
  warmup_updates: 50

checkpoint:
  keep_last_epochs: 1
  best_checkpoint_metric: acc
  maximize_best_checkpoint_metric: true
  # restore_file: ???

model:
  _name: SL_topic_detection_PerceiverIO
  dropout: 0.1
  d_model: ???
  encoder_input_embed_size: 256
  num_blocks: 1
  num_self_attends_per_block: 4
  num_self_attention_heads: 8
  num_cross_attention_heads: 8
  chunk_size_feed_forward: 256
  num_latents: 256  # has to be a multiple of chunk_size_feed_forward
  d_latents: 512
  qk_channels: 256
  v_channels: 768  # must have same value as d_latents, which is enforced in the script
  decoder_num_channels: 100  # must have same value as num_labels, which is enforced in the script
  decoder_qk_channels: 256
  decoder_v_channels: 256
  cross_attention_shape_for_attention: kv
  self_attention_widening_factor: 1
  cross_attention_widening_factor: 1
  hidden_act: relu
  attention_probs_dropout_prob: 0.1
  use_query_residual: false
  num_bands: 5
  preprocessor_position_encoding_type: trainable
  decoder_position_encoding_type: trainable
  image_prep_num_channels: 256
  image_prep_type: patches
  image_prep_spatial_downsample: 10
  image_prep_temporal_downsample: 5
  image_prep_in_channels: 3
  image_prep_out_channels: 128
  conv_after_patching: false
  conv_after_patching_in_channels: 54

bpe:
  _name: sentencepiece
  sentencepiece_model: ???
